apiVersion: v1
kind: Pod
metadata:
  name: mrt-yo-flask
  labels:
    app: psmt-test
spec:
  hostNetwork: true
  restartPolicy: Always
  containers:
  - name: psmt-container
    image: edenouob/mrt-yo-flask:20250807
    imagePullPolicy: Never
    securityContext:
      privileged: true
    command: ["/bin/bash", "-lc"]
    args:
      - >
        set -e;
        mkdir -p /workspace/Person-suitcase-motion-tracker &&
        echo "waiting for /workspace/Person-suitcase-motion-tracker/main.py ..." &&
        while [ ! -f /workspace/Person-suitcase-motion-tracker/main.py ]; do sleep 1; done &&
        cd /workspace/Person-suitcase-motion-tracker &&
        python main.py --model /model/yolo11m-seg.pt
    volumeMounts:
    - name: app-workspace
      mountPath: /workspace
  volumes:
  - name: app-workspace
    emptyDir: {}